### ISSUE TITLE
page limit function throws an error 

### ISSUE THREAD

**Issue by arnav095** [picklesueat/data_jobs_data#1]
**page limit** function throws an error whenever I try to run it.

**#to test program**    
page_limit(keyword,500, False, chromedriver path, 2.5, start_at = 0)

The above code throws a **syntax error**. Even if I rectify it, it still shows an error. For some reason, the code is not able to **identify the path of the chromedriver**. is there any way to rectify it?

**Comment by picklesueat** [comment]
https://discord.gg/python
